export default [
    "If it was about knowledge, we would all be skinny and rich. It’s not about what you know but what you do!",
    "The distance between who am I am and who I want to be is only separated by what I do!",
    "The only bad workout is the one that didn’t happen.",
    "To change your body you must first change your mind.",
    "Someone busier than you is running right now.",
    "Working out is never convenient. But neither is illness, diabetes and obesity!",
    "I don’t stop when I’m tired, I stop when I’m DONE!",
    "I don’t work hard because I hate my body. I workout because I love it!",
    "Get comfortable with being uncomfortable!",
    "When it burns, is when you’re just getting started. That’s when you get stronger!",
    "You can’t run from all your problems, but it will help you lose weight.",
    "Get started as if you are motivated. Pretend. And the motivation will come!",
    "Excuses don’t burn calories.",
    "Your body hears everything your mind says. Keep going. You can!",
    "Don’t stop until you’re proud.",
    "You don’t have to go fast, you just have to go.",
    "If you’re tired of starting over; stop giving up!",
    "On the other side of your workout is the body and health you want!",
    "The question isn’t can you, it’s will you!",
    "Workouts are like life. The harder it is, the STRONGER YOU BECOME!",
    "If no one thinks you can, then you have to!",
    "If you still look good at the end of your work out…you didn’t work hard enough!"
];
